### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by sn0vv** [vrtmrz/ring-a-secretary#1]
対話エリアが良さそうと思ってインストールしたのですが、以下のエラーが出ます。
![image](https://user-images.githubusercontent.com/10492222/230909952-61e9dca0-91c3-48d2-b549-65a0bdbec35e.png)
設定は以下のとおりです。
![image](https://user-images.githubusercontent.com/10492222/230910272-86822669-82d5-4333-8a22-42e0f2901993.png)
どうすれば使用できるでしょうか。

**Comment by vrtmrz** [comment]
こんにちは！　Modelが空欄だからだと思います。
一度、`gpt-3.5-turbo-0301`と入力して実行してみていただけますか？
（空でもできるようにするべきでしたね）
よろしくお願いします。

**Comment by sn0vv** [comment]
動作確認できました。ありがとうございます！
